node {
   def app
   stage('Preparation') {
     checkout scm
   }
   stage('Build image') {         
     app = docker.build("bambino29/docker-node-demo")    
   }
   
   stage('Push image') {
      withCredentials([string(credentialsId: 'dockerhub-passwd', variable: 'dockerhub-passwd')]) {           
         sh 'docker login -u bambino29 -p ${dockerhub-passwd}'
         sh 'docker push bambino29/docker-node-demo'
     }    
   } 
}



