node {
   def app
   stage('Preparation') {
     checkout scm
   }
   stage('Build image') {         
     app = docker.build("bambino29/docker-node-demo")    
   }
   
   stage('Push image') {
     docker.withRegistry('https://index.docker.io/v2/', 'DockerHub') {           
       app.push("${env.BUILD_NUMBER}")            
       pp.push("latest")        
     }    
   } 
}



